version: '3'
services:
    nginx_compose_service:
        container_name: nginx_compose
        image: nginx_nginx_compose_service
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./var/www/html:/var/www/html
        networks:
            - cameobridge
    python_server:
        container_name: pythonserver7
        image: python
        command: python -m http.server 3801
        ports:
            - "3801:3801"
        networks:
            - cameobridge
networks:
    cameobridge:
