# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  api_config:
  api_home:
  api_storage:

services:
  ckan_api:
    container_name: ckan_api
    image: asia.gcr.io/epa-cloud/epa_ckan:latest
    links:
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_API_PORT}:5000"
    networks:
      - epa-ckan_api
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/${CKAN_DATABASE_NAME}
      - CKAN_DATASTORE_WRITE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/${DATASTORE_DATABASE_NAME}
      - CKAN_DATASTORE_READ_URL=postgresql://${DATASTORE_READONLY_USER}:${DATASTORE_READONLY_PASSWORD}@${POSTGRES_URL}:5432/${DATASTORE_DATABASE_NAME}
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_API_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - api_config:/etc/ckan
      - api_home:/usr/lib/ckan
      - api_storage:/var/lib/ckan

  ckan:
    container_name: ckan
    image: asia.gcr.io/epa-cloud/epa_ckan:latest
    command: ["/usr/lib/ckan/venv/bin/uwsgi", "--ini-paste", "/etc/ckan/production.ini"]
    links:
      - solr
      - redis
    networks:
      - epa-nginx
      - epa-ckan
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/${CKAN_DATABASE_NAME}
      - CKAN_DATASTORE_WRITE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/${DATASTORE_DATABASE_NAME}
      - CKAN_DATASTORE_READ_URL=postgresql://${DATASTORE_READONLY_USER}:${DATASTORE_READONLY_PASSWORD}@${POSTGRES_URL}:5432/${DATASTORE_DATABASE_NAME}
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    image: asia.gcr.io/epa-cloud/datapusher:latest
    networks:
      - epa-ckan
      - epa-ckan_api
    ports:
      - "8800:8800"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800

  solr:
    container_name: solr
    image: asia.gcr.io/epa-cloud/epa_solr:latest
    networks:
      - epa-ckan
      - epa-ckan_api
    ports:
      - "127.0.0.1:8984:8983"

  redis:
    container_name: redis
    image: asia.gcr.io/epa-cloud/redis:latest
    networks:
      - epa-ckan
      - epa-ckan_api
    ports:
      - "127.0.0.1:6380:6379"

  nginx:
    container_name: nginx
    depends_on:
      - ckan
    image: asia.gcr.io/epa-cloud/epa_nginx
    networks:
      - epa-nginx
    ports:
      - "80:80"

networks:
  epa-nginx:
  epa-ckan_api:
  epa-ckan:
